### ISSUE TITLE
Complete renaming of package

### ISSUE THREAD

**Issue by blowekamp** [conda-forge/libitk-feedstock#10]
The README need to be update to properly link to the libitk packages.

The old "itk" packages need to be marked as broken.

**Comment by blowekamp** [comment]
@thewtex Can you take care of these remaining issues with the renaming?

Thanks.

**Comment by thewtex** [comment]
@blowekamp Yes, will do.

**Comment by blowekamp** [comment]
Great! Thank you.

Related there are not windows package for lobito:
https://anaconda.org/conda-forge/libitk/files

Likely caused by the non-existence of the build services for this package in appveyor:
- [x] https://circleci.com/gh/conda-forge/libitk-feedstock
- [x] https://travis-ci.org/conda-forge/libitk-feedstock
- [ ] https://ci.appveyor.com/project/conda-forge/libitk-feedstock/branch/master

While for the original itk and future itk package has travis missing:
- [X ] https://circleci.com/gh/conda-forge/itk-feedstock
- [ ] https://travis-ci.org/conda-forge/itk-feedstock
- [X] https://ci.appveyor.com/project/conda-forge/itk-feedstock/branch/master

**Comment by blowekamp** [comment]
Thanks for the fix! The README is all green now, and the builds appear to be working OK.
