### ISSUE TITLE
Reason for restricting hdf5 version

### ISSUE THREAD

**Issue by k-dominik** [conda-forge/libitk-feedstock#16]
Hey there,

is there any reason for restricting the hdf5 version to `1.8.18.*`?
I tried building it against `1.10` and it seems to work.

Cheers and thanks for maintaining the recipe

**Comment by blowekamp** [comment]
Please see #5 for the motivation.

ITK should work against it, but to build with conda pinning, the specific version is needed.

**Comment by k-dominik** [comment]
Okay, thank you very much for the swift reply and the link to the explanation. I wasn't aware of the conda pinnings, that explains it. Will build it from my own fork in the meantime. Cheers
