### ISSUE TITLE
Add selected ITK remote modules

### ISSUE THREAD

**Issue by ghisvail** [conda-forge/libitk-feedstock#59]
I have a package (`convert3d`) which requires one of the ITK remote modules (MorphologicalContourInterpolation).

Could we provide it through this recipe or should it be maintained in its own?

What do you reckon?

**Comment by ghisvail** [comment]
It turns out `convert3d` could be built without the remote module and upstream updated the build system to make it an optional dependency.

**Comment by blowekamp** [comment]
You are welcome to make a PR to enable a remote module. Some remote modules are of mixed quality, while others page behind the ITK releases,  so enabling them all is not easily done.
