### ISSUE TITLE
no hdf5 dependency on Windows

### ISSUE THREAD

**Issue by KrisThielemans** [conda-forge/libitk-feedstock#66]
I see
https://github.com/conda-forge/libitk-feedstock/blob/802bc4f174db076a2ce3240b1292b86ee3045877/recipe/meta.yaml#L26
Any particular reason for it?

**Comment by blowekamp** [comment]
I believe there was a compilation error when using the HDF5 library. You are welcomed to make a PR and [enable ITK using the system HDF5](https://github.com/conda-forge/libitk-feedstock/blob/802bc4f174db076a2ce3240b1292b86ee3045877/recipe/bld.bat#L17) to see if the error still exists.
